apiVersion: apps/v1
kind: Deployment
metadata:
  name: asset-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: asset-api
  template:
    metadata:
      labels:
        app: asset-api
    spec:
      containers:
      - name: asset-api
        image: macroray/cloud_computing_asset_mgmt-backend-api:latest
        ports:
        - containerPort: 8080